name: Swift

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'
    - name: Build
      run: swift build -v
    - name: Build-Demo
      run: |
        cd SwiftLoggerSampleApp
        xcodebuild -project SwiftLoggerSampleApp.xcodeproj -scheme "SwiftLoggerSampleApp" -destination 'generic/platform=iOS' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" archive
    - name: Run tests
      run: swift test --skip PerformanceTests
